language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install .
script:
  - pytest
changes:
  only:
  - ./mplStrater
  - ./tests
branches:
  only:
    - main
git:
  - depth: 3
notifications:
  email: false